import { chromium } from "playwright";
import { startServer, loginContext } from "./probe-helper.mjs";
const { srv, base } = await startServer(3996);
const browser = await chromium.launch(); const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
const logs = []; page.on("console", (m) => { if (m.type() === "error") logs.push(m.text()); }); page.on("pageerror", (e) => logs.push("pageerror: " + e.message));
await loginContext(page.context(), base);
await page.goto("http://127.0.0.1:3996/", { waitUntil: "networkidle" });
const box = async () => page.evaluate(() => { const s = document.getElementById("side").getBoundingClientRect(); const d = document.getElementById("dashboard").getBoundingClientRect(); return { collapsed: document.getElementById("tab-analysis").classList.contains("side-collapsed"), sideW: Math.round(s.width), sideX: Math.round(s.x), dashX: Math.round(d.x), dashW: Math.round(d.width), openBtnHidden: document.getElementById("side-open").classList.contains("hidden") }; });
console.log("before:", JSON.stringify(await box()));
await page.click("#side-toggle"); await page.waitForTimeout(400);
console.log("after collapse:", JSON.stringify(await box()));
await page.click("#side-open"); await page.waitForTimeout(400);
console.log("after reopen:", JSON.stringify(await box()));
console.log("console:", logs.join("\n") || "(чисто)");
await browser.close(); srv.kill();
